### ISSUE TITLE
Fonttikokojen määritys suhteelliseksi

### ISSUE THREAD

**Issue by nikoheikkila** [pelilegacy/wordpress#1]
Fonttikoot tulisi määrittää muilla tavoin kuin kiinteinä pikseleinä. Tämä on [yleisesti parempi käytäntö](http://www.impressivewebs.com/understanding-em-units-css/) esimerkiksi responsiivisuuden kannalta.

esim.

```css
elem {
  font-size: 1.6rem; /* tai 1.2em; */
  ...
}
```
